name: develop-CI-CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout develop
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Build project
        run: yarn && yarn build
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./dingtai
          remote: /usr/local/dingtai/frontend/nginx/nginx/client/test/
          host: ${{ secrets.DING_TAI_HOST }}
          username: ${{ secrets. DING_TAI_HOST_USERNAME }}
          password: ${{ secrets.DING_TAI_HOST_PASSWORD }}
