name: develop-CI-CD

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout develop
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Build project
        run: yarn && yarn build
      - name: SCP Command to Transfer Files
        run: |
          sshpass -p ${{ secrets.DING_TAI_HOST_PASSWORD }} scp -r ./dingtai ${{ secrets. DING_TAI_HOST_USERNAME }}@${{ secrets.DING_TAI_HOST }}:/home/
        
       
